networks:
  traefik:
    external: true

services:
  subsystem-code-server:
    image: ${IMAGE:-lscr.io/linuxserver/code-server:latest}
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: America/Phoenix
      DEFAULT_WORKSPACE: /workspace
      PROXY_DOMAIN: subsystem.mmto.arizona.edu
    volumes:
      - ${WORKSPACE_DIR:-.}:/workspace
      - ${WORKSPACE_DIR:-.}:/var/www/html/code-server
      - ./config/settings.json:/config/.config/code-server/data/User/settings.json
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.subsystem-code-server.entrypoints=websecure
        - traefik.http.routers.subsystem-code-server.rule=Host(`subsystem.mmto.arizona.edu}`) && PathPrefix(`/code-server}`)
        - traefik.http.routers.subsystem-code-server.tls.certresolver=letsencrypt
        - traefik.http.routers.subsystem-code-server.middlewares=code-server-stripprefix,authelia@file
        - traefik.http.middlewares.code-server-stripprefix.stripprefix.prefixes=/code-server
        - traefik.http.services.subsystem-code-server.loadbalancer.server.port=8443
